---
name: NLP-GATE
version: 0.1
author:
  - 'Johann Petrak <firstnameDOTlastname_AT_jpetrakDOTcom>'
abstract: Handle GATE documents and annotations
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  XML::LibXML: 0
  XML::Writer: 0
provides:
  NLP::GATE:
    file: lib/NLP/GATE.pm
    version: 0.1
  NLP::GATE::Annotation:
    file: lib/NLP/GATE/Annotation.pm
    version: 0.1
  NLP::GATE::AnnotationSet:
    file: lib/NLP/GATE/AnnotationSet.pm
    version: 0.1
  NLP::GATE::Document:
    file: lib/NLP/GATE/Document.pm
    version: 0.1
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
