--- #YAML:1.0
name:               NLP-GATE
version:            0.6
abstract:           Handle GATE documents and annotations
author:
    - Johann Petrak <firstname.lastname-at-jpetrak-dot-com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Temp:   0.18
    FindBin:      0
    Test::More:   0.92
    XML::LibXML:  1.69
    XML::Writer:  0.605
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
